### ISSUE TITLE
Unpack Error: Bakemonogatari Portable, CPKFBSTD1.18.04, DLL2.78.04

### ISSUE THREAD

**Issue by szfzafa** [kirisetsz/cpktools#1]
羽神你好，化物语PSP cpk解包出错：
T:\cpktools-master\cpktools-master>"F:\Python27\python.exe" cpkunpack.py "T:\Gamersky_Bakemonogatari
.Portable_psp\Bakemonogatari Portable\PSP_GAME\USRDIR\rom\exrom.cpk"
Read T:\Gamersky_Bakemonogatari.Portable_psp\Bakemonogatari Portable\PSP_GAME\USRDIR\rom\exrom.cpk..
# .
## Schema CpkHeader (CPK)

```
    56                 UpdateDateTime(0x00000011)
    16                       FileSize(0x00000020)
    56                  ContentOffset(0x00000029)
    56                    ContentSize(0x00000037)
    16                      TocOffset(0x00000043)
    16                        TocSize(0x0000004d)
    14                         TocCrc(0x00000055)
    16                     EtocOffset(0x0000005c)
    16                       EtocSize(0x00000067)
    56                     ItocOffset(0x00000070)
    56                       ItocSize(0x0000007b)
    14                        ItocCrc(0x00000084)
    16                     GtocOffset(0x0000008c)
    16                       GtocSize(0x00000097)
    14                        GtocCrc(0x000000a0)
    56              EnabledPackedSize(0x000000a8)
    56                EnabledDataSize(0x000000ba)
    16                  TotalDataSize(0x000000ca)
    14                           Tocs(0x000000d8)
    54                          Files(0x000000dd)
    54                         Groups(0x000000e3)
    54                          Attrs(0x000000ea)
    14                     TotalFiles(0x000000f0)
    14                    Directories(0x000000fb)
    14                        Updates(0x00000107)
    52                        Version(0x0000010f)
    52                       Revision(0x00000117)
    52                          Align(0x00000120)
    52                         Sorted(0x00000126)
    52                            EID(0x0000012d)
    54                        CpkMode(0x00000131)
    5a                          Tvers(0x00000139)
    1a                        Comment(0x0000013f)
    54                          Codec(0x00000147)
    54                        DpkItoc(0x0000014d)
```

---

```
            UpdateDateTime 0x0000000000000001
             ContentOffset 0x0000000000001000
               ContentSize 0x0000000015e19800
                ItocOffset 0x0000000000000800
                  ItocSize 0x0000000000000590
         EnabledPackedSize 0x0000000015e0b3f2
           EnabledDataSize 0x0000000015e0b3f2
                     Files 0x0000006e
                    Groups 0x00000000
                     Attrs 0x00000000
                   Version 0x0007
                  Revision 0x0000
                     Align 0x0800
                    Sorted 0x0000
                       EID 0x0000
                   CpkMode 0x00000000
                     Tvers CPKFBSTD1.18.04, DLL2.78.04(0x00000155)
                     Codec 0x00000000
                   DpkItoc 0x00000000
```
# 

Traceback (most recent call last):
  File "cpkunpack.py", line 683, in <module>
    lib[frame.typename] = frame
  File "cpkunpack.py", line 391, in **setitem**
    TableLibrary.__filter[k](s, v)
  File "cpkunpack.py", line 353, in __cpk
    s.TOC_BASELINE = min(utf.value('ContentOffset')[0], utf.value('TocOffset')[0])
IndexError: tuple index out of range

化物语PSP iso 从游民星空可以下
iso里只有3个cpk文件，都很大，每个四五百MB，羽神有空的话能否下载iso分析看看？

**Comment by renzy** [comment]
have a bunch of files that im trying to unpack. throws this error, https://pastebin.com/yHy1qxUf, for all the cpks at offset 0x2c0. if i zero out the 4 bytes at that offset it unpacks but the images corrupt and missing the PNG IHDR header stuff. tried digging into it myself but couldnt figure it out. 

attached is an example file im using.
[1000100.cpk.tar.gz](https://github.com/kirisetsz/cpktools/files/241092/1000100.cpk.tar.gz)

**Comment by jamescallen246** [comment]
任何修复？

**Comment by kamikat** [comment]
很遗憾，这个问题目前没有解决方案

**Comment by jamescallen246** [comment]
Hi, you speak English? I was able to get it to work luckily but with another tool https://github.com/morkt/GARbro/releases

**Comment by kamikat** [comment]
@jamescallen246 Thanks for the information. I'm sorry that there's no maintenance to the project for a long time. I'll try asking my friend for a CPK file to see if it works this weekend (maybe).
